### ISSUE TITLE
Make html

### ISSUE THREAD

**Issue by Ch40s1** [Ch40s1/Ecommerce-Project#1]

**Comment by Ch40s1** [comment]
![Image](https://github.com/Ch40s1/Ecommerce-Project/assets/114247747/20b9c9ef-2920-4c63-943f-aae8a456392c)
make the boilerplate for the ecommerce site.

**Comment by CrypticSinz** [comment]
issue resolved hoe

**Comment by CrypticSinz** [comment]
issue resolved
